server:
  port: 9090
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/task_manager?serverTimezone=UTC&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
